title: National Council Against Drug Abuse
url: https://ncada.org.sg
favicon: /images/NCADA_xs.png
colors:
  primary-color: "#00b2a9"
  secondary-color: "#029894"
  media-colors:
    - title: media-color-one
      color: "#49939a"
    - title: media-color-two
      color: "#014f49"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
resources_name: Resources
description: The official website of the National Council Against Drug Abuse
  (NCADA), Singapore.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3s2mqgkqocybw.amplifyapp.com/
prod: https://master.d3s2mqgkqocybw.amplifyapp.com/
shareicon: /images/NCADA_PNG_logo_RGB_2.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
